version: '3.4'

services:

  personwishlistdb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  addressdb:
    image: redis:alpine

  rabbitmq:
    image: rabbitmq:3-management-alpine

  portainer:
    image: portainer/portainer-ce

  personwishlist.api:
    image: ${DOCKER_REGISTRY-}personwishlistapi
    build:
      context: .
      dockerfile: Services/Person/Person.API/Dockerfile

  addresswishlist.api:
    image: ${DOCKER_REGISTRY-}addresswishlistapi
    build:
      context: .
      dockerfile: Services/Address/Address.API/Dockerfile

volumes:
  portainer_data:
